name: Print Software Versions

on:
  push:
    branches:
      - main

jobs:
  PrintLanguageVersions:
    runs-on: ubuntu-latest
    steps:
      - name: Print Java Version
        run: java --version
      - name: Print Node Version
        run: node --version
      - name: Print Python Version
        run: python3 --version

  PrintDBMSVersions:
    runs-on: ubuntu-latest
    needs: [PrintLanguageVersions]
    steps:
      - name: Install PostgreSQL
        run: sudo apt-get update && sudo apt-get install -y postgresql

      - name: Install MySQL
        run: sudo apt-get install -y mysql-client

      - name: Install MongoDB
        run: sudo apt-get install -y mongodb

      - name: Print PostgreSQL Version
        run: psql --version

      - name: Print MySQL Version
        run: mysql --version

      - name: Print MongoDB Version
        run: mongod --version
